title: Purdue USB
author:
  name: Purdue USB
  email: "&#117;&#x73;&#98;&#64;&#99;&#115;&#46;&#112;&#x75;&#x72;&#100;&#117;&#x65;&#x2e;&#101;&#x64;&#117;"
description: The Computer Science Undergraduate Student Board (USB) at Purdue University is the liaison between undergraduate CS/DS students and the CS department.
show_excerpts: false # set to true to show excerpts on the homepage
include: ["_pages", "_assets/searchData.js"]
url: https://purdueusb.com/

collections:
  pages:
    output: true
    permalink: /:name/
  wiki:
    output: true
    permalink: /wiki/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "wiki"
    values:
      layout: "wiki"

# Date Format
# refer to https://shopify.github.io/liquid/filters/date/ to customize this
date_format: "%B %-d, %Y"

highlighter: none
markdown: kramdown
kramdown:
  html_to_native: true

css_dir: "assets"

#ES6 in minifier
jekyll-minifier:
  uglifier_args:
    harmony: true

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-purgecss
  - jekyll-minifier
  - jekyll-redirect-from
